name: CI/CD Pipeline

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t solanamirror/frontend:latest .

    - name: Save Docker image to file
      run: docker save -o solanamirror-frontend.tar solanamirror/frontend:latest

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: solanamirror-frontend
        path: solanamirror-frontend.tar

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master' 

    steps: 
    - name: Download Docker image artifact
      uses: actions/download-artifact@v3
      with:
        name: solanamirror-frontend

    - name: Load Docker image from file
      run: docker load -i solanamirror-frontend.tar

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push solanamirror/frontend:latest